<a href="https://colab.research.google.com/github/SakshiMaholiya123/Machine-Learning/blob/linear_algebra/Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
file=pd.read_csv('hdfc_loan_dataset_full_enriched - hdfc_loan_dataset_full_enriched.csv')


In [ ]:
file.head()

,Loan_ID,Bank,Customer_Name,Gender,Married,Dependents,Education,Employment_Status,Applicant_Income,Coapplicant_Income,...,Loan_to_Annual_Income,Customer_Sentiment,Religion,State,City,PIN_Code,Aadhaar_Synthetic,Phone_Number,Email,Occupation
0,HDFC100001,HDFC Bank,Rohan Verma,Male,No,2,Graduate,Salaried,56976,0,...,11.747,Positive,Hindu,Delhi,Dwarka,857743,6.940000e+11,9068671773,rohan.verma@example.in,Farmer
1,HDFC100002,HDFC Bank,Rohan Verma,Male,No,0,Graduate,Unemployed,1856,0,...,40.381,Negative,Hindu,Punjab,Ludhiana,863836,6.330000e+11,9990772625,rohan.verma@example.in,Civil Engineer
2,HDFC100003,HDFC Bank,Aditya Nair,Female,Yes,0,Graduate,Salaried,64553,0,...,3.082,Positive,Hindu,Maharashtra,Nagpur,834796,1.660000e+11,9195085016,aditya.nair@example.in,Medical Representative
3,HDFC100004,HDFC Bank,Ananya Joshi,Male,No,0,Graduate,Salaried,88450,0,...,0.621,Negative,Hindu,Gujarat,Vadodara,438590,5.528183e+10,9179335548,ananya.joshi@example.in,Marketing Executive
4,HDFC100005,HDFC Bank,Harpreet Singh,Male,Yes,3,Graduate,Self-Employed,9539,0,...,1.736,Neutral,Sikh,West Bengal,Kolkata,495224,1.560000e+11,9795137116,harpreet.singh@example.in,Shopkeeper


In [ ]:
file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 47 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Loan_ID                      1000 non-null   object 
 1   Bank                         1000 non-null   object 
 2   Customer_Name                1000 non-null   object 
 3   Gender                       1000 non-null   object 
 4   Married                      1000 non-null   object 
 5   Dependents                   1000 non-null   int64  
 6   Education                    1000 non-null   object 
 7   Employment_Status            1000 non-null   object 
 8   Applicant_Income             1000 non-null   int64  
 9   Coapplicant_Income           1000 non-null   int64  
 10  Loan_Amount                  1000 non-null   int64  
 11  Loan_Term_Months             1000 non-null   int64  
 12  Credit_History               1000 non-null   int64  
 13  Property_Area      

In [ ]:
column = [
    'Applicant_Income','Coapplicant_Income','Loan_Amount','Loan_Term_Months',
    'Credit_History','Age','CIBIL_Score','Annual_Household_Income','Debt_to_Income_Ratio',
    'Existing_EMIs','Number_of_Previous_Loans','Default_History_Count',
    'Employment_Length_Years','Asset_Value','Monthly_Expense','Loan_to_Annual_Income'
]

In [ ]:
df=file[column]

In [ ]:
df

,Applicant_Income,Coapplicant_Income,Loan_Amount,Loan_Term_Months,Credit_History,Age,CIBIL_Score,Annual_Household_Income,Debt_to_Income_Ratio,Existing_EMIs,Number_of_Previous_Loans,Default_History_Count,Employment_Length_Years,Asset_Value,Monthly_Expense,Loan_to_Annual_Income
0,56976,0,8031545,360,1,36,699,683712,0.098,5610,0,0,1,744861,30391,11.747
1,1856,0,899361,240,1,42,707,22272,4.939,9166,1,0,0,0,1856,40.381
2,64553,0,2387748,60,1,38,641,774636,0.000,0,2,0,1,2913766,24557,3.082
3,88450,0,658856,12,1,32,677,1061400,0.301,26613,1,0,3,3488244,36750,0.621
4,9539,0,198671,36,0,35,594,114468,0.000,0,0,0,2,472179,3920,1.736
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,44713,0,5883603,360,1,35,707,536556,0.116,5165,1,0,2,1895538,11899,10.965
996,70886,0,2780228,300,0,37,561,850632,0.284,20102,1,0,1,2413969,32458,3.268
997,24392,11337,301249,24,1,28,725,428748,0.966,34514,2,0,0,1631635,22977,0.703
998,64803,94136,719891,48,1,33,679,1907268,0.214,34000,1,0,4,5000832,72376,0.377


In [ ]:
mat=np.array(df)

In [ ]:
mat

array([[5.697600e+04, 0.000000e+00, 8.031545e+06, ..., 7.448610e+05,
        3.039100e+04, 1.174700e+01],
       [1.856000e+03, 0.000000e+00, 8.993610e+05, ..., 0.000000e+00,
        1.856000e+03, 4.038100e+01],
       [6.455300e+04, 0.000000e+00, 2.387748e+06, ..., 2.913766e+06,
        2.455700e+04, 3.082000e+00],
       ...,
       [2.439200e+04, 1.133700e+04, 3.012490e+05, ..., 1.631635e+06,
        2.297700e+04, 7.030000e-01],
       [6.480300e+04, 9.413600e+04, 7.198910e+05, ..., 5.000832e+06,
        7.237600e+04, 3.770000e-01],
       [2.293800e+04, 0.000000e+00, 6.101900e+04, ..., 0.000000e+00,
        1.610500e+04, 2.220000e-01]])

average of the applicant income column

In [ ]:
average_applicant=np.mean(mat[:,0])

In [ ]:
print(average_applicant)

42430.057


Find max value from Loan_Amount column.

In [ ]:
max_value=df['Loan_Amount'].max()

In [ ]:
print('maximum value present in the loan amout is ',max_value)

maximum value present in the loan amout is  13790960


using numpy


In [ ]:
maximum_value=np.max(mat[:,2])

In [ ]:
print(maximum_value)

13790960.0


vector addition
adding applicant income and co applicant income

In [ ]:
applicant_income=np.array(df['Applicant_Income'])
Coapplicant_income=np.array(df['Coapplicant_Income'])
total=applicant_income+Coapplicant_income
total


array([ 56976,   1856,  64553,  88450,   9539,  39184,  81223,      0,
        17675,  71409,  46972,  38126,  63115,  35034,  53684, 113545,
        29319,  10609,  66474,  95054,  48611,  15509, 117255,  97735,
        45050,  34900,   9381,   3000,  54597,  43481, 143023,  42416,
        92535,  39270,  55899,  33527,  28605,  33983,  23543, 129184,
         3000,  60010,  42393,  48860,  66608,  27205,  52863,  53000,
        91498,  47655,  92893,   1519,  80579,  94207,  55058,  23796,
        33925,  31372, 212945,  39035, 135891,  33478,  46668,  45832,
       136339,  29274,  89323,  66933,  36203,  52935,  33160,   9768,
        85714, 119391,  21455,  36438,  40206,  38127,  12104,      0,
        71887, 112111,   5000,   3000,  28345,   7914,  89966, 101852,
        13318,  80548,  62827,   3884,  21109,  45652,  60198,  13049,
        99076,  99781,  83511,   4812,  82923, 157182,  32371,  13956,
        86493, 108790, 101761,  98367,   7781, 144852,  79239,  92625,
      

vector subtraction

In [ ]:
expense=np.array(df['Monthly_Expense'])


In [ ]:
savings=total-expense
savings

array([ 26585,      0,  39996,  51700,   5619,  21411,  44078,      0,
         6020,  45192,  35961,  11610,  37146,  20899,  20675,  66848,
        19635,   8609,  41242,  45608,  23656,  12432,  59418,  47545,
        29897,  28549,   7287,      0,  38303,  17167,  87206,  33739,
        48197,  17477,  19230,  16207,  16715,  19916,   6978,  75256,
            0,  30413,  22098,  24590,  32924,  13586,  31722,  22566,
        45901,  28549,  50633,      0,  51629,  53078,  31002,  11539,
        24163,  20933, 119874,  14904,  68647,  19997,  31859,  25823,
        76530,  10424,  46010,  38252,  19929,  28410,  13807,   3905,
        38294,  60474,  10887,  21560,  26064,  27539,      0,      0,
        43251,  68376,      0,   1000,  21045,   4321,  44171,  58858,
        11318,  41852,  24008,      0,  11657,  22359,  34710,   8093,
        60894,  58191,  45008,   2812,  46377,  90470,  19387,   2141,
        52562,  76769,  60283,  53279,   4096,  84704,  33755,  42385,
      


Get CIBIL score of first customer

In [ ]:
first_cibil=np.array(df['CIBIL_Score'])[0]

Scalar multiplication on applicant income column


In [ ]:
scalar_value=3
scale_res=scalar_value*np.array(df['Applicant_Income'])
scale_res

array([170928,   5568, 193659, 265350,  28617, 117552, 243669,      0,
        53025, 214227,  76659, 114378, 189345,  53880, 161052, 168276,
        87957,  31827, 114810, 129879, 145833,  46527, 169458, 293205,
       135150, 104700,  28143,   9000, 163791, 130443, 269376,  68919,
       277605, 117810, 167697, 100581,  85815, 101949,  70629, 387552,
         9000, 180030,  91518, 146580, 186855,  81615, 158589, 159000,
       274494, 142965, 278679,   4557, 241737, 282621,  82938,  71388,
       101775,  94116, 363528, 117105, 205863,  76851,  90264, 137496,
       244137,  87822, 197160, 200799, 108609, 158805,  45819,  15000,
       159315, 159198,  64365, 109314, 120618, 114381,  36312,      0,
       215661, 336333,  15000,   9000,  85035,  23742, 269898, 305556,
        22821, 187746, 188481,   9000,  63327, 136956, 180594,  26766,
       208845, 299343, 250533,   9000, 248769, 319254,  97113,  41868,
       259479, 224664, 131154, 295101,  23343, 179694, 237717, 277875,
      

In [ ]:
print(first_cibil)

699


Matrix transpose

In [ ]:
transpose_mat=mat.T

In [ ]:
transpose_mat

array([[5.697600e+04, 1.856000e+03, 6.455300e+04, ..., 2.439200e+04,
        6.480300e+04, 2.293800e+04],
       [0.000000e+00, 0.000000e+00, 0.000000e+00, ..., 1.133700e+04,
        9.413600e+04, 0.000000e+00],
       [8.031545e+06, 8.993610e+05, 2.387748e+06, ..., 3.012490e+05,
        7.198910e+05, 6.101900e+04],
       ...,
       [7.448610e+05, 0.000000e+00, 2.913766e+06, ..., 1.631635e+06,
        5.000832e+06, 0.000000e+00],
       [3.039100e+04, 1.856000e+03, 2.455700e+04, ..., 2.297700e+04,
        7.237600e+04, 1.610500e+04],
       [1.174700e+01, 4.038100e+01, 3.082000e+00, ..., 7.030000e-01,
        3.770000e-01, 2.220000e-01]])

inverse of matrix


In [ ]:
inverse=np.linalg.inv(mat)

LinAlgError: Last 2 dimensions of the array must be square

In [ ]:
rank=np.linalg.matrix_rank(mat)

In [ ]:
print(rank)

15


Find Customers Older Than Average

In [ ]:
age=np.array(df['Age'])

In [ ]:
aver=np.mean(age)
print('average age is ',aver)
res=np.array(age>aver)
print(res)




average age is  34.412
[ True  True  True False  True False  True False False  True  True False
  True  True False  True False  True False False False  True  True False
  True False False False False False  True  True  True False False False
  True False False False  True False False  True  True False  True  True
  True  True  True  True False  True  True False False  True  True False
 False  True  True  True  True  True  True False False False False False
 False  True  True False  True False False False False  True  True  True
 False False False False  True  True  True  True  True False  True  True
  True False  True False False  True  True False  True  True  True False
  True  True  True False  True  True False  True  True False  True  True
 False False False False False  True False False False False  True False
 False  True  True False False  True  True False  True  True False False
  True  True  True False  True  True False  True  True False False  True
  True False  True  True Fal

Find dot product between:

income vector
asset vector

In [ ]:
asset=np.array(df['Asset_Value'])
income=np.array(df['Applicant_Income'])
dot_prod=np.dot(asset,income)
print(dot_prod)

115006885431768


Find magnitude of income vector.

In [ ]:
magnitude=np.linalg.norm(income)
magnitude

np.float64(1609657.046589428)

Find Column-wise Mean


In [ ]:
average=np.mean(mat,axis=0)
average

array([4.24300570e+04, 9.72711400e+03, 2.21671290e+06, 1.59132000e+02,
       7.23000000e-01, 3.44120000e+01, 6.53013000e+02, 6.25886052e+05,
       1.48118157e+02, 1.81733900e+04, 8.65000000e-01, 1.47000000e-01,
       2.43400000e+00, 1.90804169e+06, 2.36034270e+04, 1.01631030e+01])

In [ ]:
matA = np.array(df[['Applicant_Income', 'Asset_Value']])
matB = np.array(df[['Existing_EMIs', 'Debt_to_Income_Ratio']])
matA
matB

array([[5.6100e+03, 9.8000e-02],
       [9.1660e+03, 4.9390e+00],
       [0.0000e+00, 0.0000e+00],
       ...,
       [3.4514e+04, 9.6600e-01],
       [3.4000e+04, 2.1400e-01],
       [1.5226e+04, 6.6400e-01]])

In [ ]:
addition_mat=matA+matB
addition_mat

array([[6.25860000e+04, 7.44861098e+05],
       [1.10220000e+04, 4.93900000e+00],
       [6.45530000e+04, 2.91376600e+06],
       ...,
       [5.89060000e+04, 1.63163597e+06],
       [9.88030000e+04, 5.00083221e+06],
       [3.81640000e+04, 6.64000000e-01]])

matrix subtraction



In [ ]:
mat_sub=matA-matB
mat_sub

array([[ 5.13660000e+04,  7.44860902e+05],
       [-7.31000000e+03, -4.93900000e+00],
       [ 6.45530000e+04,  2.91376600e+06],
       ...,
       [-1.01220000e+04,  1.63163403e+06],
       [ 3.08030000e+04,  5.00083179e+06],
       [ 7.71200000e+03, -6.64000000e-01]])

matrix multiplication

In [ ]:
mat_multi=np.dot(matA.T,matB)
mat_multi

array([[7.76060727e+11, 1.56940352e+07],
       [3.48109838e+13, 1.96706342e+10]])

row sum of matrix A

In [ ]:
row_sum=np.sum(matA,axis=1)
row_sum

array([ 801837,    1856, 2978319, 3576694,  481718, 1438867, 2149986,
        662552,  591908, 2875991, 1640927, 1291966, 1359211, 1828572,
        941299, 4882838, 1227390, 1234875, 2007073, 3221879, 1680947,
        958196, 5464830, 3578941, 1631012, 1765108,  171034,  859022,
       1514036, 1683242, 4151458,  673395, 3898884, 1552269, 1595917,
       1344342, 1563453,  798045, 1128727, 4380659,   90189, 2774064,
       1467783, 1979182, 3067750, 1327006, 1440142, 2167109, 4291272,
        960463, 2904259,  649718, 3536053, 4705535, 2266504,  286652,
       2069423, 1507967, 7121579,  926007, 5726072, 1834729, 2076308,
       1825393, 4549352,  476909, 4187035, 1923366,  930411, 2502969,
        709376,    5000, 3029943, 4312223, 2065668, 1200505, 1673839,
       1583787,  631491,  132577, 2965390, 3901931,  452586,    3000,
       1634387,  565960, 2425939, 3753451,  607290, 3504573, 2812124,
        281512,  781136, 1744568, 2844886,  624551, 3033215, 3807247,
       2286076,    3